In [1]:
import numpy as np

In [2]:
def my_arange(number):
    arange = np.full(int(number),int(number)) - np.arange(1, int(number)+1)
    return(arange)

In [3]:
my_arange(10)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [4]:
import numpy as np

A = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
B = np.array([4, 12, -3])
X = np.linalg.inv(A).dot(B)
print(X)

[ 0.46666667  3.84444444 -5.55555556]


In [5]:
def my_matrix(number):
    matrix = np.diag(my_arange(int(number)))
    return(matrix)
matrix = my_matrix(11)
matrix

array([[10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [6]:
np.trace(matrix)

55

In [11]:
import pandas as pd
import requests
import _io
import zipfile
from _io import (DEFAULT_BUFFER_SIZE, BlockingIOError, UnsupportedOperation,
                 open, open_code, FileIO, BytesIO, StringIO, BufferedReader,
                 BufferedWriter, BufferedRWPair, BufferedRandom,
                 IncrementalNewlineDecoder,TextIOWrapper)


def get_zip_files():
    response = requests.get('http://files.grouplens.org/datasets/movielens/ml-latest-small.zip')
    return zipfile.ZipFile(BytesIO(response.content))


def get_ratings_data_frame(zip_arch):
    """
    :return: pandas data frame with movies ratings
    """
    return pd.read_csv(zip_arch.open(name='ml-latest-small/ratings.csv'))


def get_movies_data_frame(zip_arch):
    """
    :return: pandas data frame with movies
    """
    return pd.read_csv(zip_arch.open(name='ml-latest-small/movies.csv'))


movies_zip = get_zip_files()
ratings = get_ratings_data_frame(movies_zip)
movies_info = get_movies_data_frame(movies_zip).set_index(keys='movieId', drop=False)

top_films = ratings.query('rating == {}'.format(5))

best_film_id = top_films['movieId'].value_counts().idxmax()

print(f'Top movie: {movies_info.loc[best_film_id, "title"]}')



Top movie: Shawshank Redemption, The (1994)


In [12]:
import numpy as np
from scipy.spatial.distance import cdist

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ],
    np.int32
)

next_user_stats = np.array([[0, 1, 2, 0, 0, 0]])
Y = cdist(next_user_stats, users_stats, 'cosine')
idx = np.argmin(Y)
print(users_stats[idx, :])

[0 1 1 0 0 0]


In [17]:
power_data = pd.read_csv('power.csv')
sub_data = power_data.query('country in ("Latvia", "Lithuania", "Estonia") '
                            '& category in (4, 12, 21) & 2005 < year < 2010 & quantity >= 0')

print(f"Total power consumption: {sub_data['quantity'].sum()}")



Total power consumption: 164555.0
